# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestDemo():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_demo(self):
        self.driver.get("https://ithelp.ithome.com.tw/")
        self.driver.set_window_size(1552, 832)
        self.driver.find_element(By.LINK_TEXT, "技術文章").click()
        elements = self.driver.find_elements(By.XPATH, "//h2[contains(.,\'技術文章\')]")
        assert len(elements) > 0
        self.driver.close()
